name: BasicTests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  BasicTests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install boost
        run: sudo apt install -y libboost-all-dev
      - name: Configure
        run: ./configure
      - name: Install
        run: make install
      - name: Run test
        run: make basic_test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: tst/basic_test.cpp
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
