name: Polytope110

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Poly110:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install boost
        run: sudo apt install -y libboost-all-dev
      - name: Configure
        run: ./configure
      - name: Install
        run: make install
      - name: Run test
        run: make poly110_test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: tst/poly110.cpp
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
